site_name: Dev Blueprint
site_url: https://dev-blueprint.readthedocs.io/en/latest/

extra_css:
  - stylesheets/extra.css

theme:
  icon:
    logo: material/library-outline

  font:
    text: Work Sans
    code: Roboto Mono

  features:
    - navigation.instant
    - navigation.instant.progress

  name: material

  palette: 
    - scheme: slate
      primary: black

nav:
  - Manifest: index.md
  - Fundamentals:
    - The Blueprint: fundamentals/the-blueprint.md
    - Python: fundamentals/python.md
  - Resources:
    - Get what is yours: resources/index.md
  - Repositories:
    - Python: repositories/python.md
    - TypeScript: repositories/typescript.md
  - Course:
    - GitHub Organization: course/organization.md

markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences
  - pymdownx.blocks.details
